name = "slash-create-worker"
type = "javascript"
account_id = ""
workers_dev = true

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[env.development]
vars = { COMMANDS_DEV_GUILD = "" }